import Problem56.PaperV7.SamplingInterfaceBridges
#print axioms Problem56.PaperV7.general_sampling_joint
#print axioms Problem56.PaperV7.general_sampling_joint_saturated
#print axioms Problem56.PaperV7.sampling_lower_count_tail_bound_sharp
#print axioms Problem56.PaperV7.sampling_pointwise_saturated_sharp
#print axioms Problem56.PaperV7.general_sampling_saturated_sharp
#print axioms Problem56.PaperV7.general_sampling_joint_saturated_sharp
#print axioms Problem56.PaperV7.saturated_upper_quadraticForm_chain
